spring:
  application:
    name: scw-ui
    
  redis:
    host: 192.168.229.129
    port: 6379
  thymeleaf:
    cache: false #开发时禁用
  session:
    store-type: redis
    timeout: 1800
      

feign:
  hystrix:
    enabled: true

server:
  port: 10000

eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/